### ISSUE TITLE
Does not work with `actions/checkout` set `persistent-credentials: false`

### ISSUE THREAD

**Issue by taku1201** [Songmu/tagpr#233]
Hi, I'm reporting an issue discovered in tagpr v1.8.1.
When tagpr is executed on my private repository with `persistent-credentials: false` set in `actions/checkout`,
it fails with the following error message when running `git remote show origin`:

```
git [remote show origin]
fatal: could not read Username for ‘https://github.com’: No such device or address
failed to detect default branch: exit status 128
```

This likely occurs because credentials are not properly set when executing the command. 
Therefore, I appreciate that credentials would be configured properly.

**Comment by Songmu** [comment]
Thank you for trying `persist-credentials: false` promptly! This was an implementation oversight bug. I've fixed it in #234 and released v1.8.2. Please take a look.

**Comment by taku1201** [comment]
I appreciate your prompt action.
However, the issue still doesn't seem to be resolved.
I've attached the execution logs, and I hope they are helpful.

[4_tagpr.txt](https://github.com/user-attachments/files/22203254/4_tagpr.txt)

**Comment by taku1201** [comment]
I tested the functionality in my private repository using the following conditions:

* `actions/checkout@v5.0.0`
    * with `persist-credentials: false`
* `Songmu/tagpr@v1.8.4`

The results confirmed that it behaves as expected.

I greatly appreciate the prompt action taken.
